# Override the port Tomcat listens on
server:
  port: 9080

# Another implementation of getObservablePrimes() above that's causing Http response 503
# org.springframework.web.context.request.async.AsyncRequestTimeoutException
# https://stackoverflow.com/questions/39856198/recurring-asyncrequesttimeoutexception-in-spring-boot-admin-log
# https://stackoverflow.com/questions/53650303/spring-boot-timeout-when-using-futures/53652640
spring:
  mvc:
    async:
      request-timeout: -1

# NOTE: Using embedded MongoDB with flapdoodle for Reactive Mongo simulation
# See `readme.md` about the 2 ways of simulating Reactive Mongo using installed MongoDB vs embedded MongoDB with flapdoodle
#  data:
#    mongodb:
#      authentication-database: admin
#      host: localhost
#      port: 27017
#      username: test
#      password: password
#      database: test

# NOTE: Using H2 blocking DB to simulate access with Reactor Flux/Mono to be non-blocking IO
  datasource:
    url: jdbc:h2:file:~/Documents/h2TestDB
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 100
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show_sql: true
  h2:
    console:
      enabled: true

# Customize log levels
logging:
  level:
    reactor:
      core: TRACE
      util: TRACE
    org:
#      springframework.data: INFO
    io:
      netty: DEBUG
      reactor: DEBUG
    com:
      giocosmiano: DEBUG

# JWT secret key
jwtSecretKey: Th1s1sAV3ryL0ngSecretKeyIndeed!!$


# enable actuator endpoints
#endpoints.autoconfig.enabled=true
#endpoints.beans.enabled=true
#endpoints.configprops.enabled=true
#endpoints.env.enabled=true
#endpoints.health.enabled=true
#endpoints.info.enabled=true
#endpoints.metrics.enabled=true
#endpoints.mappings.enabled=true
#endpoints.trace.enabled=true
