# Override the port Tomcat listens on
server:
  port: 9080

# Another implementation of getObservablePrimes() above that's causing Http response 503
# org.springframework.web.context.request.async.AsyncRequestTimeoutException
# https://stackoverflow.com/questions/39856198/recurring-asyncrequesttimeoutexception-in-spring-boot-admin-log
# https://stackoverflow.com/questions/53650303/spring-boot-timeout-when-using-futures/53652640
spring:
  mvc:
    async:
      request-timeout: -1

# Customize log levels
logging:
  level:
    reactor:
      core: TRACE
      util: TRACE
    org:
      springframework.data: TRACE
    io:
      netty: DEBUG
      reactor: DEBUG
    com:
      giocosmiano: DEBUG

# enable actuator endpoints
#endpoints.autoconfig.enabled=true
#endpoints.beans.enabled=true
#endpoints.configprops.enabled=true
#endpoints.env.enabled=true
#endpoints.health.enabled=true
#endpoints.info.enabled=true
#endpoints.metrics.enabled=true
#endpoints.mappings.enabled=true
#endpoints.trace.enabled=true
